import os
import yaml
import csv

# List of IDs to search for
ids_to_search_for = [
    'azure.ad_hybrid_health_service.service_members_data', 
    'azure.ad_hybrid_health_service.services_monitoring_configuration', 
    'azure.advisor.prediction', 
    'azure.aks.agent_pools_machines', 
    'azure.aks.managed_clusters_tags', 
    'azure.aks.resolve_private_link_service_id', 
    'azure.aks.snapshots_tags', 
    'azure.alerts_management.alerts', 
    'azure.alerts_management.smart_groups', 
    'azure.api_management.authorization_login_links', 
    'azure.api_management.operations_results', 
    'azure.api_management.perform_connectivity_check', 
    'azure.api_management.policy_restriction_validations', 
    'azure.api_management.tenant_access_git', 
    'azure.api_management.tenant_configuration', 
    'azure.api_management.user_confirmation_password', 
    'azure.app_service.check_name_availability', 
    'azure.app_service.container_apps_revisions', 
    'azure.app_service.diagnostics', 
    'azure.app_service.environments_ase_networking_configuration', 
    'azure.app_service.move', 
    'azure.app_service.plans_vnet_route', 
    'azure.app_service.static_sites_static_site_user', 
    'azure.app_service.static_sites_user_roles_invitation_link', 
    'azure.app_service.static_sites_zip_deployment_for_static_site', 
    'azure.app_service.static_sites_zip_deployment_for_static_site_build', 
    'azure.app_service.update_publishing_user', 
    'azure.app_service.update_source_control', 
    'azure.app_service.validate', 
    'azure.app_service.validate_move', 
    'azure.app_service.verify_hosting_environment_vnet', 
    'azure.app_service.web_apps_backup', 
    'azure.app_service.web_apps_backup_slot', 
    'azure.app_service.web_apps_diagnostic_logs_config', 
    'azure.app_service.web_apps_diagnostic_logs_config_slot', 
    'azure.app_service.web_apps_function_secret', 
    'azure.app_service.web_apps_function_secret_slot', 
    'azure.app_service.web_apps_host_secret', 
    'azure.app_service.web_apps_host_secret_slot', 
    'azure.app_service.web_apps_instance_ms_deploy_operation', 
    'azure.app_service.web_apps_instance_ms_deploy_operation_slot', 
    'azure.app_service.web_apps_ms_deploy_operation', 
    'azure.app_service.web_apps_ms_deploy_operation_slot', 
    'azure.app_service.web_apps_one_deploy_operation', 
    'azure.app_service.web_apps_swift_virtual_network', 
    'azure.app_service.web_apps_swift_virtual_network_connection_with_check', 
    'azure.app_service.web_apps_swift_virtual_network_connection_with_check_slot', 
    'azure.app_service.web_apps_swift_virtual_network_slot', 
    'azure.app_service.workflows', 
    'azure.application_insights.components_tags', 
    'azure.application_insights.web_tests_tags', 
    'azure.authorization.access_review_history_definition', 
    'azure.authorization.access_review_history_definition_instance', 
    'azure.authorization.access_review_instance', 
    'azure.authorization.global_administrator', 
    'azure.authorization.scope_access_review_history_definition', 
    'azure.authorization.scope_access_review_history_definition_instance', 
    'azure.authorization.scope_access_review_instance', 
    'azure.automation.dsc_configuration_content', 
    'azure.automation.job_output', 
    'azure.automation.job_runbook_content', 
    'azure.automation.node_reports_content', 
    'azure.automation.private_link_resources', 
    'azure.automation.runbook_content', 
    'azure.automation.runbook_draft_content', 
    'azure.azure_arc_data.data_controllers', 
    'azure.batch.location', 
    'azure.batch.network_security_perimeter', 
    'azure.billing.address', 
    'azure.billing.available_balances', 
    'azure.billing.policies', 
    'azure.billing_benefits.savingsplan', 
    'azure.bot_service.direct_line', 
    'azure.bot_service.email_sign_in_url', 
    'azure.cdn.afd_profiles', 
    'azure.cdn.check_endpoint_name_availability', 
    'azure.cdn.check_name_availability', 
    'azure.cdn.check_name_availability_with_subscription', 
    'azure.cdn.validate_probe', 
    'azure.cloud_shell.delete_console_with_location', 
    'azure.cloud_shell.delete_user_settings_with_location', 
    'azure.cloud_shell.get_console_with_location', 
    'azure.cloud_shell.get_user_settings_with_location', 
    'azure.cloud_shell.keep_alive_with_location', 
    'azure.cloud_shell.patch_user_settings_with_location', 
    'azure.cloud_shell.put_console_with_location', 
    'azure.cloud_shell.put_user_settings_with_location', 
    'azure.compute.cloud_services_instances', 
    'azure.compute.cloud_services_update_domain', 
    'azure.compute.gallery_sharing_profile', 
    'azure.compute.log_analytics', 
    'azure.compute.virtual_machine_scale_set_rolling_upgrades', 
    'azure.compute.virtual_machine_scale_sets_instances', 
    'azure.computeschedule.scheduled_actions', 
    'azure.confidential_ledger.name_availability', 
    'azure.consumption.aggregated_cost', 
    'azure.consumption.balances', 
    'azure.consumption.marketplaces', 
    'azure.consumption.reservation_recommendations', 
    'azure.consumption.usage_details', 
    'azure.container_apps.functions_extension', 
    'azure.container_apps.namespaces', 
    'azure.container_apps.revisions', 
    'azure.container_apps.subscriptions', 
    'azure.container_instances.containers', 
    'azure.container_instances.subnet_service_association_link', 
    'azure.cosmos_db.cassandra_resources', 
    'azure.cosmos_db.cassandra_resources_cassandra_keyspace_throughput', 
    'azure.cosmos_db.cassandra_resources_cassandra_table_throughput', 
    'azure.cosmos_db.cassandra_resources_cassandra_view_throughput', 
    'azure.cosmos_db.gremlin_resources', 
    'azure.cosmos_db.gremlin_resources_gremlin_database_throughput', 
    'azure.cosmos_db.gremlin_resources_gremlin_graph_throughput', 
    'azure.cosmos_db.mongodb_resources', 
    'azure.cosmos_db.mongodb_resources_mongodb_collection_throughput', 
    'azure.cosmos_db.mongodb_resources_mongodb_database_throughput', 
    'azure.cosmos_db.sql_resources', 
    'azure.cosmos_db.sql_resources_sql_container_throughput', 
    'azure.cosmos_db.sql_resources_sql_database_throughput', 
    'azure.cosmos_db.table_resources', 
    'azure.cosmos_db.table_resources_table_throughput', 
    'azure.cost_management.dimensions', 
    'azure.cost_management.forecast', 
    'azure.cost_management.generate_benefit_utilization_summaries_report', 
    'azure.cost_management.generate_cost_details_report_operation', 
    'azure.cost_management.generate_detailed_cost_report_operation', 
    'azure.cost_management.generate_reservation_details_report', 
    'azure.cost_management.price_sheet', 
    'azure.cost_management.query', 
    'azure.customer_lockbox.post', 
    'azure.customer_lockbox.requests_status', 
    'azure.data_box.service', 
    'azure.data_box_edge.device_capacity_check', 
    'azure.data_box_edge.devices_security_settings', 
    'azure.data_box_edge.support_packages', 
    'azure.data_explorer.database', 
    'azure.data_factory.activity_runs', 
    'azure.data_factory.data_flow_debug_session', 
    'azure.data_factory.exposure_control', 
    'azure.data_factory.integration_runtimes_linked_integration_runtime', 
    'azure.data_factory.pipelines_run', 
    'azure.data_factory.trigger_runs', 
    'azure.data_migration.sql_migration_services_node', 
    'azure.data_protection.data_protection', 
    'azure.data_protection.export_jobs', 
    'azure.data_protection.restorable_time_ranges', 
    'azure.data_replication.tenant', 
    'azure.data_share.email_registrations', 
    'azure.data_transfer.azure_data_transfer', 
    'azure.defender.tasks', 
    'azure.delegated_network.controller', 
    'azure.desktop_virtualization.app_attach_package_info', 
    'azure.desktop_virtualization.control_session_host_update', 
    'azure.desktop_virtualization.initiate_session_host_update', 
    'azure.desktop_virtualization.msix_images', 
    'azure.desktop_virtualization.session_host', 
    'azure.dev_center.check_name_availability', 
    'azure.dev_center.check_scoped_name_availability', 
    'azure.dev_test_labs.labs_environment', 
    'azure.dev_test_labs.policy_sets', 
    'azure.device_update.check_name_availability', 
    'azure.device_update.private_endpoint_connection_proxies_private_endpoint_properties', 
    'azure.devops_infrastructure.subscription_usages', 
    'azure.dns.resource_reference', 
    'azure.engagement_fabric.name_availability', 
    'azure.event_hubs.application_group_application_group', 
    'azure.event_hubs.network_security_perimeter_configurations', 
    'azure.front_door.endpoints', 
    'azure.front_door.name_availability', 
    'azure.front_door.name_availability_with_subscription', 
    'azure.hdinsight.clusters_auto_scale_configuration', 
    'azure.hdinsight.clusters_identity_certificate', 
    'azure.hdinsight.locations', 
    'azure.hdinsight.virtual_machines', 
    'azure.hybrid_aks.delete_kubernetes_versions', 
    'azure.hybrid_aks.delete_vm_skus', 
    'azure.hybrid_aks.get_kubernetes_versions', 
    'azure.hybrid_aks.get_vm_skus', 
    'azure.hybrid_aks.put_kubernetes_versions', 
    'azure.hybrid_aks.put_vm_skus', 
    'azure.hybrid_cloud.cloud_connections_tags', 
    'azure.hybrid_cloud.cloud_connectors_tags', 
    'azure.hybrid_connectivity.generate_aws_template', 
    'azure.hybrid_connectivity.service_configurations_orupdate', 
    'azure.hybrid_network.artifact_manifests_state', 
    'azure.hybrid_network.artifact_stores_network_fabric_controller_end_points', 
    'azure.hybrid_network.configuration_group_schemas_state', 
    'azure.hybrid_network.configuration_group_values_tags', 
    'azure.hybrid_network.network_function_definition_versions_state', 
    'azure.hybrid_network.network_functions_tags', 
    'azure.hybrid_network.network_service_design_versions_state', 
    'azure.hybrid_network.proxy_artifact_state', 
    'azure.hybrid_network.site_network_services_tags', 
    'azure.hybrid_network.sites_tags', 
    'azure.iot_hub.iot_hub', 
    'azure.key_vault.vaults_access_policy', 
    'azure.log_analytics.gateways', 
    'azure.log_analytics.query_packs_tags', 
    'azure.log_analytics.query_packs_without_name', 
    'azure.log_analytics.shared_keys', 
    'azure.log_analytics.workspace_purge', 
    'azure.logic_apps.integration_service_environment_network_health', 
    'azure.machine_learning.web_services_regional_properties', 
    'azure.maintenance.apply_updates_or_cancel', 
    'azure.maintenance.scheduled_event', 
    'azure.managed_applications.applications_access', 
    'azure.managed_applications.operations', 
    'azure.managed_identity.system_assigned_identities', 
    'azure.managed_network_fabric.access_control_lists_administrative_state', 
    'azure.managed_network_fabric.external_networks_administrative_state', 
    'azure.managed_network_fabric.external_networks_static_route_bfd_administrative_state', 
    'azure.managed_network_fabric.internal_networks_administrative_state', 
    'azure.managed_network_fabric.internal_networks_bgp_administrative_state', 
    'azure.managed_network_fabric.internal_networks_static_route_bfd_administrative_state', 
    'azure.managed_network_fabric.l2_isolation_domains_administrative_state', 
    'azure.managed_network_fabric.l3_isolation_domains_administrative_state', 
    'azure.managed_network_fabric.network_devices_administrative_state', 
    'azure.managed_network_fabric.network_fabrics_infra_management_bfd_configuration', 
    'azure.managed_network_fabric.network_fabrics_workload_management_bfd_configuration', 
    'azure.managed_network_fabric.network_interfaces_administrative_state', 
    'azure.managed_network_fabric.network_tap_rules_administrative_state', 
    'azure.managed_network_fabric.network_taps_administrative_state', 
    'azure.managed_network_fabric.network_to_network_interconnects_administrative_state', 
    'azure.managed_network_fabric.network_to_network_interconnects_npb_static_route_bfd_administrative_state', 
    'azure.managed_network_fabric.route_policies_administrative_state', 
    'azure.management_groups.check_name_availability', 
    'azure.management_groups.management_group_subscriptions', 
    'azure.management_groups.tenant_backfill', 
    'azure.maria_db.check_name_availability', 
    'azure.maria_db.private_endpoint_connections_tags', 
    'azure.maria_db.recommended_action_sessions', 
    'azure.maria_db.reset_query_performance_insight_data', 
    'azure.media_services.locations', 
    'azure.media_services.tracks_track_data', 
    'azure.migrate.dependency_map_controller', 
    'azure.migrate.hyperv_dependency_map_controller', 
    'azure.migrate.hyperv_dependency_map_controller_dependency_map_status', 
    'azure.migrate.hyperv_machines_controller_properties', 
    'azure.migrate.import_sites_controller_imported_machines', 
    'azure.migrate.server_dependency_map_controller', 
    'azure.migrate.server_sites_controller_dependency_map_status', 
    'azure.migrate.server_sites_controller_properties', 
    'azure.migrate.vmware_properties_controller_dependency_map_status', 
    'azure.migrate.vmware_properties_controller_properties', 
    'azure.migrate.vmware_properties_controller_run_as_account', 
    'azure.migrate.vmware_properties_controller_tags', 
    'azure.migrate.web_app_properties_controller_properties', 
    'azure.migrate_projects.database_instances', 
    'azure.migrate_projects.databases', 
    'azure.migrate_projects.events', 
    'azure.migrate_projects.machines', 
    'azure.migrate_projects.migrate_projects', 
    'azure.migrate_projects.solutions', 
    'azure.mixed_reality.proxy', 
    'azure.ml_services.compute_custom_services', 
    'azure.ml_services.compute_data_mounts', 
    'azure.ml_services.compute_idle_shutdown_setting', 
    'azure.ml_services.connection_rai_blocklist_item_bulk', 
    'azure.ml_services.managed_network_provisions', 
    'azure.mobile_network._tags', 
    'azure.mobile_network.attached_data_networks_tags', 
    'azure.mobile_network.data_networks_tags', 
    'azure.mobile_network.packet_core_control_planes_tags', 
    'azure.mobile_network.packet_core_data_planes_tags', 
    'azure.mobile_network.services_tags', 
    'azure.mobile_network.sim_groups_tags', 
    'azure.mobile_network.sim_policies_tags', 
    'azure.mobile_network.sites_packet_core', 
    'azure.mobile_network.sites_tags', 
    'azure.mobile_network.slices_tags', 
    'azure.monitor.action_groups_notifications_at_action_group_resource_level', 
    'azure.monitor.create_notifications_at_tenant_action_group_resource_level', 
    'azure.monitor.get_test_notifications_at_tenant_action_group_resource_level', 
    'azure.monitor.private_link_scopes_tags', 
    'azure.monitor.scheduled_query_rule', 
    'azure.mpc_network_function.network_functions_tags', 
    'azure.mysql.advanced_threat_protection_settings_put', 
    'azure.mysql.backup_and_export', 
    'azure.mysql.check_name_availability', 
    'azure.mysql.check_name_availability_without_location', 
    'azure.mysql.check_virtual_network_subnet_usage', 
    'azure.mysql.get_private_dns_zone_suffix', 
    'azure.mysql.long_running_backup', 
    'azure.mysql.servers_migration', 
    'azure.network.application_gateways_tags', 
    'azure.network.application_security_groups_tags', 
    'azure.network.azure_firewalls_tags', 
    'azure.network.bastion_hosts_tags', 
    'azure.network.check_dns_name_availability', 
    'azure.network.connection_monitors_tags', 
    'azure.network.custom_ip_prefixes_tags', 
    'azure.network.ddos_custom_policies_tags', 
    'azure.network.ddos_protection_plans_tags', 
    'azure.network.express_route_circuits_tags', 
    'azure.network.express_route_cross_connections_tags', 
    'azure.network.express_route_gateways_tags', 
    'azure.network.express_route_ports_tags', 
    'azure.network.express_route_provider_ports', 
    'azure.network.firewall_policies_tags', 
    'azure.network.firewall_policy_deployments', 
    'azure.network.flow_logs_tags', 
    'azure.network.generatevirtualwanvpnserverconfigurationvpnprofile', 
    'azure.network.interfaces_tags', 
    'azure.network.ip_allocations_tags', 
    'azure.network.ip_groups_groups', 
    'azure.network.load_balancers_tags', 
    'azure.network.local_network_gateways_tags', 
    'azure.network.manager_active_configurations', 
    'azure.network.manager_active_connectivity_configurations', 
    'azure.network.manager_commits', 
    'azure.network.manager_effective_connectivity_configuration', 
    'azure.network.manager_effective_security_admin_rules', 
    'azure.network.nat_gateways_tags', 
    'azure.network.p2s_vpn_gateways_tags', 
    'azure.network.profiles_tags', 
    'azure.network.public_ip_addresses_tags', 
    'azure.network.public_ip_prefixes_tags', 
    'azure.network.route_filters_tags', 
    'azure.network.route_tables_tags', 
    'azure.network.security_groups_tags', 
    'azure.network.security_partner_providers_tags', 
    'azure.network.service_endpoint_policies_tags', 
    'azure.network.supported_security_providers', 
    'azure.network.virtual_appliances_tags', 
    'azure.network.virtual_hubs_tags', 
    'azure.network.virtual_network_gateway_connections_tags', 
    'azure.network.virtual_network_gateways_tags', 
    'azure.network.virtual_network_taps_tags', 
    'azure.network.virtual_networks_tags', 
    'azure.network.virtual_wans_tags', 
    'azure.network.vpn_gateways_tags', 
    'azure.network.vpn_server_configurations_associated_with_virtual_wan', 
    'azure.network.vpn_server_configurations_tags', 
    'azure.network.vpn_sites_configuration', 
    'azure.network.vpn_sites_tags', 
    'azure.network.watchers_tags', 
    'azure.network_analytics.data_types_data', 
    'azure.network_function.azure_traffic_collectors_tags', 
    'azure.network_function.collector_policies_tags', 
    'azure.nexus.clusters_version', 
    'azure.orbital.contact_profiles_tags', 
    'azure.orbital.spacecrafts_tags', 
    'azure.peering.check_service_provider_availability', 
    'azure.peering.looking_glass', 
    'azure.portal_services.portal_tenant', 
    'azure.postgresql.check_name_availability', 
    'azure.postgresql.check_name_availability_with_location', 
    'azure.postgresql.customoperation', 
    'azure.postgresql.flexible_server', 
    'azure.postgresql.get_private_dns_zone_suffix', 
    'azure.postgresql.location_based_capabilities', 
    'azure.postgresql.private_endpoint_connection', 
    'azure.postgresql.virtual_network_subnet_usage', 
    'azure.postgresql_hsc.configurations_on_coordinator', 
    'azure.postgresql_hsc.configurations_on_node', 
    'azure.powerbi_embedded.operations', 
    'azure.powerbi_embedded.workspace_collections', 
    'azure.provider_hub.manifest', 
    'azure.purview.features', 
    'azure.purview.ingestion_private_endpoint_connections_status', 
    'azure.quantum.workspace', 
    'azure.quantum.workspaces_tags', 
    'azure.recovery_services.recovery_services', 
    'azure.recovery_services.registered_identities', 
    'azure.recovery_services.vault_certificates', 
    'azure.recovery_services_backup.backup_operation_results', 
    'azure.recovery_services_backup.backups', 
    'azure.recovery_services_backup.data_move', 
    'azure.recovery_services_backup.feature_support', 
    'azure.recovery_services_backup.fetch_tiering_cost', 
    'azure.recovery_services_backup.item_level_recovery_connections', 
    'azure.recovery_services_backup.job_cancellations', 
    'azure.recovery_services_backup.job_operation_results', 
    'azure.recovery_services_backup.jobs', 
    'azure.recovery_services_backup.operation', 
    'azure.recovery_services_backup.protection_container_refresh_operation_results', 
    'azure.recovery_services_backup.recovery_point', 
    'azure.recovery_services_backup.restores', 
    'azure.recovery_services_backup.validate_operation', 
    'azure.recovery_services_site_recovery.replication_protected_items_appliance', 
    'azure.recovery_services_site_recovery.replication_protected_items_mobility_service', 
    'azure.reservations.applied_reservation', 
    'azure.reservations.calculate_exchange', 
    'azure.reservations.calculate_refund', 
    'azure.reservations.catalog', 
    'azure.reservations.exchange', 
    'azure.reservations.return', 
    'azure.scom.instances_log_analytics', 
    'azure.security.alerts_resource_group_level_state_to_activate', 
    'azure.security.alerts_resource_group_level_state_to_dismiss', 
    'azure.security.alerts_resource_group_level_state_to_in_progress', 
    'azure.security.alerts_resource_group_level_state_to_resolve', 
    'azure.security.alerts_subscription_level_state_to_activate', 
    'azure.security.alerts_subscription_level_state_to_dismiss', 
    'azure.security.alerts_subscription_level_state_to_in_progress', 
    'azure.security.alerts_subscription_level_state_to_resolve', 
    'azure.security.pricings', 
    'azure.security.tasks_resource_group_level_task_state', 
    'azure.security.tasks_subscription_level_task_state', 
    'azure.security_and_compliance.services', 
    'azure.sentinel.content_package', 
    'azure.sentinel.entities', 
    'azure.sentinel.threat_intelligence_indicator_indicator', 
    'azure.serial_console.serial_console', 
    'azure.service_bus.migration_configs_and_start_migration', 
    'azure.service_connector.linkers', 
    'azure.service_fabric_managed_clusters.managed_apply_maintenance_window', 
    'azure.service_fabric_managed_clusters.node_types_node', 
    'azure.service_fabric_managed_clusters.operation_results', 
    'azure.software_plan.software_plan', 
    'azure.spring_apps.build_service', 
    'azure.spring_apps.build_service_agent_pool_put', 
    'azure.spring_apps.config_servers_patch', 
    'azure.spring_apps.config_servers_put', 
    'azure.spring_apps.eureka_servers_patch', 
    'azure.spring_apps.eureka_servers_put', 
    'azure.spring_apps.gateways_capacity', 
    'azure.spring_apps.monitoring_settings_patch', 
    'azure.spring_apps.monitoring_settings_put', 
    'azure.sql.database_encryption_protectors', 
    'azure.sql.database_sql_vulnerability_assessment_execute_scan', 
    'azure.sql.managed_database_recommended_sensitivity_labels', 
    'azure.sql.managed_instance_tde_certificates', 
    'azure.sql.recommended_sensitivity_labels', 
    'azure.sql.tde_certificates', 
    'azure.sql.virtual_clusters_dns_servers', 
    'azure.sql.vulnerability_assessment_baselines', 
    'azure.sql.vulnerability_assessment_execute_scan', 
    'azure.sql.vulnerability_assessment_rule_baselines', 
    'azure.sql.vulnerability_assessments', 
    'azure.sql_vm.sql_virtual_machine_troubleshoot', 
    'azure.storage_cache.storage_target', 
    'azure.subscription.policy', 
    'azure.subscription.subscription', 
    'azure.support.look_up_resource_id', 
    'azure.support.problem_classifications_no_subscription', 
    'azure.support.service_classifications', 
    'azure.support.service_classifications_no_subscription', 
    'azure.synapse.integration_runtime_credentials', 
    'azure.synapse.kusto_pool_child_resource', 
    'azure.synapse.sql_pool_recommended_sensitivity_labels', 
    'azure.system_center_vm_manager.virtual_machine_instances_checkpoint', 
    'azure.terraform.export_terraform', 
    'azure.video_analyzer.locations', 
    'azure.voice_services.name_availability'
]

# Directory containing the OpenAPI YAML files
input_directory = '/mnt/c/LocalGitRepos/stackql/openapi-conversion/stackql-azure-openapi/openapi/src/azure/v00.00.00000/services'

# Output CSV file
output_csv = 'output.csv'

# Function to parse YAML and search for resources
def parse_yaml_file(file_path):
    with open(file_path, 'r') as file:
        try:
            return yaml.safe_load(file)
        except yaml.YAMLError as e:
            print(f"Error parsing YAML file {file_path}: {e}")
            return None

# Function to process the OpenAPI specs and generate CSV rows
def process_specs(directory, ids_to_search_for):
    csv_rows = []

    for filename in os.listdir(directory):
        if filename.endswith('.yaml'):
            file_path = os.path.join(directory, filename)
            yaml_content = parse_yaml_file(file_path)
            if yaml_content is None:
                continue
            
            # Extracting the service name (file name without .yaml)
            service_name = filename.replace('.yaml', '')

            # Traverse the x-stackQL-resources section
            resources = yaml_content.get('components', {}).get('x-stackQL-resources', {})
            for resource_name, resource_data in resources.items():
                resource_id = resource_data.get('id')
                
                if resource_id in ids_to_search_for:
                    methods = resource_data.get('methods', {})
                    for method_name, method_data in methods.items():
                        operation_id = method_data.get('operation', {}).get('operationId')
                        ref = method_data.get('operation', {}).get('$ref')
                        csv_rows.append([service_name, resource_name, method_name, operation_id, ref, True])
                else:
                    methods = resource_data.get('methods', {})
                    for method_name, method_data in methods.items():
                        operation_id = method_data.get('operation', {}).get('operationId')
                        ref = method_data.get('operation', {}).get('$ref')
                        csv_rows.append([service_name, resource_name, method_name, operation_id, ref, False])
    return csv_rows

# Writing the CSV output
def write_to_csv(csv_rows, output_file):
    with open(output_file, mode='w', newline='') as file:
        writer = csv.writer(file)
        # Writing the header row
        writer.writerow(['Service', 'Resource', 'Method', 'OperationId', 'Path', 'IsOrphaned'])
        # Writing the data rows
        writer.writerows(csv_rows)

if __name__ == '__main__':
    csv_rows = process_specs(input_directory, ids_to_search_for)
    write_to_csv(csv_rows, output_csv)
    print(f"CSV output written to {output_csv}")
